### ISSUE TITLE
Getting golang unmarshall number error

### ISSUE THREAD

**Issue by Savemech** [trivigy/discord-resource#3]
Hi there! Thanks for awesome work, starting to set-up additionals pylons into my concourse pipeline and facing followed error:
```
panic: json: cannot unmarshal number into Go struct field Params.channel of type string

goroutine 1 [running]:
main.main()
	/go/src/discord-resource/out/main.go:57 +0x6ad
```
![image](https://user-images.githubusercontent.com/8943498/60163857-24225900-9805-11e9-8c0e-ad9558070e72.png)

My channel iD is 18 character long number, any ideas how to fix?

**Comment by trivigy** [comment]
@Savemech Hey sorry don't have notifications here and totally missed this. Is this still relevant problem? Seems like an old issue and probably you resolved it.

If you still need help post the structure/string that is being passed and un-marshalled. I'll take a look at it. Otherwise feel free to close the issue.

**Comment by Savemech** [comment]
Yeah, problem still persist
